### ISSUE TITLE
T3 invention costs missing relic costs

### ISSUE THREAD

**Issue by eve-n0rman** [Kyria/LazyBlacksmith#39]
Unlike T2 invention, where the cost to produce a BPC is minimal, in T3 invention, the relic cost is often a substantial part of the invention cost.   That cost isn't currently accounted for in the invention calculator.

**Comment by Kyria** [comment]
never thought of that (as I never did t3 invention)... going to add it, thanks :)

**Comment by Kyria** [comment]
Ok, I've added the relic itself to the material list (for invention), so at least it's taken into account for the price. 

Must be good now :)
