### ISSUE TITLE
New T3 components

### ISSUE THREAD

**Issue by eve-n0rman** [Kyria/LazyBlacksmith#40]
With this weeks release, T3C hulls have new racial components on the blueprint (Superconducting [Gravimetric, Ladar, Magnetometric, Radar] Amplifiers).

**Comment by Kyria** [comment]
they should already be there, as it's related to the SDE, which I updated almost as soon as steve released its conversions.

[Example for the loki](https://khon.space/blueprint/manufacturing/29991):
```
R.A.M.- Starship Tech 15
Emergent Neurovisual Interface 2
Fullerene Intercalated Sheets 8
Metallofullerene Plating 16
Electromechanical Interface Nexus 8
Neurovisual Output Analyzer 2
Nanowire Composites 21
Fulleroferrocene Power Conduits 3
Superconducting Ladar Amplifier 12
```

Can you check if its good ?

**Comment by eve-n0rman** [comment]
Sure enough.  I could have sworn when I looked yesterday they weren't there.  Apologies!

**Comment by Kyria** [comment]
No problems, at least I double checked I did the update :D thanks anyway for the report
