### ISSUE TITLE
Trouble borrowing some code...

### ISSUE THREAD

**Issue by EricE** [Kyria/LazyBlacksmith#44]
Following you from esipy...  I spent a good part of today trying to add your approach to configuring Celery to a new app.  I was following this:  https://blog.miguelgrinberg.com/post/celery-and-the-flask-application-factory-pattern but had problems getting tasks configured (circular imports I think) and I also like the way your app is structured.  I am a HW guy in my day job and my Python skills are intermediate at best, I'm also mostly on Windows using Py3.6 in Anaconda.  I did get Celery running with Miguel's approach so Celery should be working.

My problem is now that I've dropped in your celery_app.py code, the worker won't start; it looks like it isn't configured properly:

    celery worker -A celery_worker.celery_app --loglevel=info

     -------------- celery@Eric-PC v3.1.25 (Cipater)
    ---- **** -----
    --- * ***  * -- Windows-7-6.1.7601-SP1
    -- * - **** ---
    - ** ---------- [config]
    - ** ---------- .> app:         __main__:0x45412d0
    - ** ---------- .> transport:   amqp://guest:**@localhost:5672//
    - ** ---------- .> results:     disabled://
    - *** --- * --- .> concurrency: 8 (prefork)
    -- ******* ----
    --- ***** ----- [queues]
     -------------- .> celery           exchange=celery(direct) key=celery
    [tasks]
      . tasks.update_trader

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "d:\svnrepo\projects-sw\eve_esi\trunk\env\lib\site-packages\billiard\fork
    ing.py", line 459, in main
        self = load(from_parent)
    ModuleNotFoundError: No module named 'app_web'

The transport looks wrong, in my config:  CELERY_BROKER_URL = 'sqla+sqlite:///tasks.sqlite'

'app_web' is my equivalent to lazyblacksmith

I have to use Celery 3.1.25 since there is a Windows bug in 4.1 that they aren't very motivated to fix.  Because of this, in extension\celery_app.py, I had to change:

    self.config_from_object(app.config, namespace='CELERY')  to

    self.config_from_object(app.config)  #TODO: for 4.1, namespace='CELERY')
    Also tried:  self.conf.update(app.config)

In my worker I do:

    celery_app.init_app(app)
    print('CELERY_BROKER_URL: '+celery_app.conf['CELERY_BROKER_URL'])

    And get:  CELERY_BROKER_URL: sqla+sqlite:///tasks.sqlite  so it seems to be getting the config info?

Any ideas on where I've gone wrong?

**Comment by EricE** [comment]
Switched back to Miguel's approach and now Celery is running:

    - ** ---------- .> app:         app_web:0x3549690
    - ** ---------- .> transport:   sqla+sqlite:///tasks.sqlite
and I see that the app name is also different, Miguel uses:

    celery_app = Celery(__name__, broker=Config.CELERY_BROKER_URL)
http://docs.celeryproject.org/en/latest/userguide/application.html#main-name  which explains the difference in the app name.  For the broker configuration, it looks like CELERY_BROKER_URL is an environment variable and should be replaced in the config file by BROKER_URL; then I can remove it from the above.  This also fixes the broker when I run your code.

Still have the error in forking.py:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "d:\svnrepo\projects-sw\eve_esi\trunk\env\lib\site-packages\billiard\forking.py", line 459, in main
        self = load(from_parent)
    ModuleNotFoundError: No module named 'app_web'

My worker code:
https://gist.github.com/EricE/09b3c0f16dc9e6795056256de59a764d

My extension.celery_app code;
https://gist.github.com/EricE/a10aeb9d821f7ec064a3915bb369bd40

create_app code:
https://gist.github.com/EricE/c549f6d1d3968010c3eb272a372c375e

Real life intrudes, I'll come back to it later

**Comment by Kyria** [comment]
Hello,

I didn't have time to look fully at this (i'll do this later) but keep in mind that: 
- I wrote all this for celery 4.0 (readme is not yet uptodate)
- celery 4+ is deprecated / not officially supported on windows (never worked for me) 

Also LB do not work (unless you change a few things) on py3 iirc, (i'm a bit lazy to update the few things tbh).

I'll check again later (didn't see this issue earlier sorry)

**Comment by EricE** [comment]
Thanks for the reply.  To be clear, I'm not trying to run LB, just figure out how you are configuring Flask to work with Celery.  I get a an error using your code but Miguel Grinberg's code runs so hopefully the version of Celery is ok, but I have trouble integrating tasks with his code...  I really like how clean looking your app is and am using it to learn how to write a non-trivial Flask app so I'd like to get your approach to work.

**Comment by EricE** [comment]
Just in case a fellow Windows users stumbles across this.  The problem seems to be related with Celery, Windows and multiprocessing (in the form of Celery's version, Billiard).  I was able to get the worker to run by appending -P solo:

celery worker -A celery_worker.celery_app --loglevel=info -P solo

This is not recommended for anything serious so I've also installed VMware Player and Mint so I can move this to its preferred environment...
