### ISSUE TITLE
esi-skills.read_skills.v1 invalidating periodically due to too many errors

### ISSUE THREAD

**Issue by eve-n0rman** [Kyria/LazyBlacksmith#51]
There have been some recent changes in the get_characters_character_id_skills endpoint that could be causing this.  When I re-validate, it will eventual invalidate again after some period (hours not minutes).

![screenshot](https://i.imgur.com/3U8bKhr.png)

**Comment by Kyria** [comment]
Sadly, I already saw it too but didn't have the time to fix it yet (also it's related to #50). 
I'll try to do it as soon as I can. 

Thanks for the report :)

**Comment by Kyria** [comment]
This is fixed. Should work as intended now :)
