### ISSUE TITLE
'Outpost construction' giving TE bonus on structures

### ISSUE THREAD

**Issue by ficti0n1** [Kyria/LazyBlacksmith#53]
This skill does nothing but allow you to use BPs. It does not give TE bonus.

**Comment by Kyria** [comment]
I think someone already reported it to me once ? Can't remember who, but thanks for making the issue :)

**Comment by ficti0n1** [comment]
Me via tweetfleet i think. but a few months ago

**Comment by ficti0n1** [comment]
Any update? This site had a lot of steam but feels a little neglected the past few months sadly :(

**Comment by Kyria** [comment]
sadly, no... Didn't want to invest time for this, mostly because of IRL and the fact I almost don't play anymore eve. 
I'll try to take a look at it, as I still need to make some updates to the tool (because I don't use ESI yet for everything for example), but... /shrug

**Comment by ficti0n1** [comment]
Bug still persistent.

**Comment by Kyria** [comment]
It's fixed in the dev branch, but didn't pushed it yet to the master actually.
