### ISSUE TITLE
Cost / ME - Missing functionality

### ISSUE THREAD

**Issue by charliedimaggio** [Kyria/LazyBlacksmith#54]
It doesn't seem to be possible to set this feature to consider Citadels and different ME rigs that are available. The number of runs in a batch also affect the profitability of the ME level. Currently, the only way you can explore this is on the manufacturing tab by tweaking the settings. Would it be possible to have this integrated into the current Cost / ME tab in the research section so that it is more complete?

**Comment by Kyria** [comment]
Yep, good idea. At the time I wrote that part citadels wasn't already a thing actually.
