### ISSUE TITLE
Not remembering System for Components

### ISSUE THREAD

**Issue by ficti0n1** [Kyria/LazyBlacksmith#58]
Seems to remember the station/system fine for the BP itself, but not for where the components for an item are built.

This affects tax as it defaults to Jita showing it as much more expensive then it would be if built in another system.

**Comment by Kyria** [comment]
Actually, I don't really understand that issue: i just tried to set a random system in the component system (in the settings) and it was applied fine in the BP components when I opened one, the same way when I changed it when I use the bp...

Can you explain it a bit better ?

**Comment by ficti0n1** [comment]
Sorry about that. Yep here goes.

When logged in the site remembers which system you last choose as the system on where you want to build stuff. This becomes your default system between items.

But it doesn't remember the system for where you build components and will always revert back to Jita.
