### ISSUE TITLE
Owned reaction formulas counted as bpo

### ISSUE THREAD

**Issue by Krzemien97** [Kyria/LazyBlacksmith#61]
When you own a reaction formula Lazy Blacksmith allows me to use "manufacture" and "research" option, thus redirecting to bad gateway page.

![image](https://user-images.githubusercontent.com/44144273/48986278-3f17d800-f113-11e8-853d-fdd99815f3cd.png)

**Comment by Kyria** [comment]
I fixed it, i'll deploy it when i'm done with some other changes.
I also changed the badge, so we can identify a little more easily reactions. (I still need to work on a better  "owned blueprint UI"...) 
![image](https://user-images.githubusercontent.com/1838373/49228341-70cac080-f3eb-11e8-9d66-0dc14f67cef2.png)

**Comment by Kyria** [comment]
This should be fixed with the last deployement i've made. Thanks for reporting the issue !
