### ISSUE TITLE
Calculation for Advanced Component is wrong

### ISSUE THREAD

**Issue by zhlzhl123** [Kyria/LazyBlacksmith#67]
For example for one Basilisk, number for all components that is more than 300 is wrong.

**Comment by Kyria** [comment]
You will need to explain a bit, what is wrong ? Because right now I have no idea what to check and where to compare that value... 

Quantity ? Price ? In what context (station, player structure...) etc ?
What is expected as result for example ?

**Comment by zhlzhl123** [comment]
For example:
![image](https://user-images.githubusercontent.com/24950039/59147255-40468d80-89f1-11e9-8c0d-1825ea96f137.png)

![FireShot Capture 014 - Lazy Blacksmith __ Manufacturing __ Basilisk Blueprint - khon space](https://user-images.githubusercontent.com/24950039/59147228-f067c680-89f0-11e9-832e-70a96deca143.png)

The result should be:

Gravimetric Sensor Cluster:
420	Hypersynaptic Fibers
248	Nanotransistors
4617	Titanium Carbide

Quantum Microprocessor:
2865	Nanotransistors
2865	Nonlinear Metamaterials
8595	Phenolic Composites
24352	Titanium Carbide

**Comment by Kyria** [comment]
I will have to dig for that bug. I just tried with the same t2 comps and got the same kind of issue with a raitaru in high sec. 

Probably round() issue somewhere. 

Thanks for reporting :)

**Comment by zhlzhl123** [comment]
Thanks, I like your website! The interface is simple and efficient!

BTW, It is possible to combine the calculation for the reaction with the calculation for T2 production? Like finding the raw moon material needed.

**Comment by Kyria** [comment]
if you mean having reaction stuff in t2 prod, it's possible, but it'll generate a lot of complexity and in most cast it'll be useless to people. So I won't do it, especially since it's 2 different processes that requires different structures :)

**Comment by Kyria** [comment]
I know it has been a long time, but (i hope) it is fixed :) (I tried a few things, like the basi, some t2 comps, t1 ship with many many runs, all which had some differences before I fixed it)

Make sure to clear all browser cache to see the change (else you might still load the old javascripts)

Thanks for reporting, sorry for the delay to fix it !
