### ISSUE TITLE
Prices are not updating

### ISSUE THREAD

**Issue by Overlorder1** [Kyria/LazyBlacksmith#68]
Prices are not updating.

**Comment by Kyria** [comment]
Hello,

thanks for the report. I'll have to investigate as I can't seem to find quickly the issue (and as i'm not at home for a week).

I'll try to fix this asap

**Comment by Kyria** [comment]
it's fixed. Looks like some tasks were blocked and the updating didn't happen anymore... 
Thanks for the report :)
