### ISSUE TITLE
Settings not updating

### ISSUE THREAD

**Issue by Zyles** [Kyria/LazyBlacksmith#70]
If I click the cogwheel and change rigs on a structure the material list requirements are not changing.

I tried hitting "Apply" and "Apply to all blueprints".

**Comment by Kyria** [comment]
Hello, 

I just tried and have no issue...

What browser are you using (name + version if possible) ?
Did you try to clear your browser cache ? 
If you open the developer tab (usually F12) do you see any error when you load the page ? 
Are you using a proxy ? 

Thanks :)
