### ISSUE TITLE
Time lag in Forge market prices

### ISSUE THREAD

**Issue by Austrotaxus** [Kyria/LazyBlacksmith#71]
Hello!

There is a 1-month time lag of updating the prices for the Forge region. Is this a normal behaviour? 

![Снимок экрана от 2019-12-04 18-30-30](https://user-images.githubusercontent.com/20223858/70161266-74f78100-16c4-11ea-8897-5cab3cdd3e63.png)

![изображение](https://user-images.githubusercontent.com/20223858/70160938-f6024880-16c3-11ea-8606-3259d5ae56f0.png)

**Comment by Kyria** [comment]
No it's not. 

I've fixed it (some price fetching were blocked for some reasons... I really need to take time to improve this task thing #50 ...) 

Thanks for reporting the problem !
