### ISSUE TITLE
Invention cost - show the cost per T2 manufacturing run

### ISSUE THREAD

**Issue by FroutSarain** [Kyria/LazyBlacksmith#80]
Sample case: https://khon.space/blueprint/invention/1116

In this case, the T2 BPC gives 10 manufacturing runs - we already have in the table:
* the `Invention cost`
* the `Chance`
* the `Product Price / Run`, which is the product of the 2 values above

We're missing the Invention Cost per manufacturing run, which in this case would be `Product Price / Run` / 10.

This is to answer the following question:

> how much does invention cost me per T2 item produced

**Comment by Kyria** [comment]
If you want the "Invention Cost / manuf. run", shouldn't it just be the Invention Cost divided by the number of runs ? 
So in your example, `Invention Cost` / 10 instead of `Prodduct Price / Run` / 10 ?

**Comment by Kyria** [comment]
Added in latest release (1.0.3)
