### ISSUE TITLE
Failure while executing 'npm run dist'

### ISSUE THREAD

**Issue by 4tt1c** [Kyria/LazyBlacksmith#88]
Below you can find the log output and the error which is preventing to execute 'npm run dist'

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'js-main'
1 verbose cli ]
2 info using npm@6.14.9
3 info using node@v14.15.2
4 verbose run-script [ 'prejs-main', 'js-main', 'postjs-main' ]
5 info lifecycle lazyblacksmith@1.1.0~prejs-main: lazyblacksmith@1.1.0
6 info lifecycle lazyblacksmith@1.1.0~js-main: lazyblacksmith@1.1.0
7 verbose lifecycle lazyblacksmith@1.1.0~js-main: unsafe-perm in lifecycle true
8 verbose lifecycle lazyblacksmith@1.1.0~js-main: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/blacksmith/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/blacksmith/node_modules/.bin:/var/www/blacksmith/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle lazyblacksmith@1.1.0~js-main: CWD: /var/www/blacksmith
10 silly lifecycle lazyblacksmith@1.1.0~js-main: Args: [ '-c', 'npm-run-all js-concat js-minify' ]
11 silly lifecycle lazyblacksmith@1.1.0~js-main: Returned: code: 134  signal: null
12 info lifecycle lazyblacksmith@1.1.0~js-main: Failed to exec js-main script
13 verbose stack Error: lazyblacksmith@1.1.0 js-main: `npm-run-all js-concat js-minify`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid lazyblacksmith@1.1.0
15 verbose cwd /var/www/blacksmith
16 verbose Linux 4.15.0
17 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "js-main"
18 verbose node v14.15.2
19 verbose npm  v6.14.9
20 error code ELIFECYCLE
21 error errno 134
22 error lazyblacksmith@1.1.0 js-main: `npm-run-all js-concat js-minify`
22 error Exit status 134
23 error Failed at the lazyblacksmith@1.1.0 js-main script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]
```

I'm working with Ubuntu 18.04
Any solutions for this problem?

**Comment by Kyria** [comment]
Can you maybe explain what you did all the way?
What npm version do you have ?

Did you do `npm install` in the root folder before doing `npm run dist`

**Comment by 4tt1c** [comment]
Hey Kyria, thank you for the reply.

I strictly followed your installation guide:
```
git clone https://github.com/Kyria/LazyBlacksmith.git /var/www/blacksmith
cd /var/www/blacksmith
virtualenv env
source env/bin/activate
pip3 install -U -r requirements/global-requirements.txt
pip3 install -U -r requirements/mysql-requirements.txt
cp config.dist config.py
... Filed in the required informations
python manage.py db upgrade
python manage.py sde_import -d
npm install
npm run dist
```
I'm using these versions
```
2 info using npm@6.14.9
3 info using node@v14.15.2
```

**Comment by Kyria** [comment]
I just did the test using the same exact version you use... still don't have any issue :/ 
```bash
$ npm -v  
6.14.9
$ node -v 
v14.15.2
```

are you sure the `npm install` didn't have any failure / error whatever when you tried ? 
No issues with folder rights / owners ?

**Comment by 4tt1c** [comment]
I've checked everything twice and can't find any errors.
But now i've made it again from scratch but havn't changed the cloning target, so the projects root dir is `LazyBlacksmith` now.

First time i tried `npm run dist` i got an error again, but this time with exit code `-11`. Since this haven't made any sense to me, i retried it and it ran through without exceptions. So for now it looks quiet good.

I know it is not failure-related but i'm not very familiar with webservers, so would you be so kind and support me with a nginx config, so i can finalize the setup and reply if `npm run dist` really worked!?

**Comment by Kyria** [comment]
you can check if it has worked just by running the app with `DEBUG=False` in the config (which then will use the compiled css/js)

If you use uwsgi + nginx, please have a look here: https://www.digitalocean.com/community/tutorials/how-to-set-up-uwsgi-and-nginx-to-serve-python-apps-on-ubuntu-14-04 (there's probably a more recent one, but the nginx/uwsgi part should be the same)
if you use gunicorn + nginx, you can check this https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-18-04

**Comment by 4tt1c** [comment]
Yes it is and now i know why...

There is a limitation for spawning child processes, hard coded by the hosting provider. Maybe to prevent using the server for DDoS attacks. They will not lift the limit, so `npm run dist` will never start working.
I would've loved to use your tool. Thank you for your work und your support.

Stay healthy,
7o

**Comment by Kyria** [comment]
ah !

You can maybe solve that issue by running each step separately 
```
npm run js-concat 
npm run js-minify
npm run css-build
npm run css-concat
npm run css-minify
```

Thanks for the explanation at least :)

**Comment by 4tt1c** [comment]
It's been a while but i gave it another try and i just want to let you know, that your step by step instructions worked like a charm.
