### ISSUE TITLE
New Ship Blueprint changes implemented

### ISSUE THREAD

**Issue by Tommy-Immeo** [Kyria/LazyBlacksmith#95]
Not sure if this the place for it but would be greatly appreciated if the new Ship BPO changes were implemented, screenshot of a BMO for fx. a Raven currently through https://lazy-blacksmith.space . This doesn't correlate with the current in-game BMO of a Raven.

![image](https://user-images.githubusercontent.com/80403759/116392516-d3288500-a820-11eb-9797-985ff9709359.png)

![image](https://user-images.githubusercontent.com/80403759/116392862-416d4780-a821-11eb-9fae-50c0ed098f02.png)

Thanks!

**Comment by Kyria** [comment]
you need to contact https://forums.eveonline.com/u/Rihan_Shazih in the game or on slack for this.
As i'm not maintaining it anymore (i mean the website) i can't update it
